# Generated by Django 4.0.5 on 2022-07-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0013_alter_employee_role_alter_position_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('clock_in', models.DateTimeField(blank=True)),
                ('lunch_in', models.DateTimeField(blank=True)),
                ('lunch_out', models.DateTimeField(blank=True)),
                ('clock_out', models.DateTimeField(blank=True)),
                ('total', models.IntegerField()),
                ('employeee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.employee')),
            ],
        ),
    ]
