# Generated by Django 4.0.5 on 2022-07-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecard',
            old_name='employeee',
            new_name='employee',
        ),
    ]
