# Generated by Django 4.0.5 on 2022-07-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_rename_employeee_timecard_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='clock_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='clock_out',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='lunch_in',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='lunch_out',
            field=models.TimeField(blank=True),
        ),
    ]
