# Generated by Django 4.0.5 on 2022-07-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_alter_timecard_clock_in_alter_timecard_clock_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='lunch_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='lunch_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
