# Generated by Django 4.0.5 on 2022-06-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='home_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='department',
            name='office_address',
        ),
    ]
