# Generated by Django 4.0.5 on 2022-06-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_position_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.enterprise'),
        ),
    ]
