# Generated by Django 4.0.5 on 2022-07-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_position_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
