# Generated by Django 4.0.5 on 2022-07-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=models.SET(''), to='company.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=models.SET(''), to='company.enterprise'),
        ),
    ]
